# PTB virome project
# 05_network_analysis.R
# Differential bacteria/virus selection, occurrence filtering, Spearman
# correlations, BH correction, and network-derived plots.

rm(list = ls())

source("script/config.R")

library(tidyverse)
library(Maaslin2)
library(igraph)
library(ggraph)
library(ggplot2)
library(ggtext)
library(patchwork)

metadata <- read.delim(METADATA_FILE, check.names = FALSE, stringsAsFactors = FALSE)
votu <- read.delim(VOTU_FILE, check.names = FALSE, row.names = 1)
bacteria <- read.delim(BACTERIAL_FILE, check.names = FALSE, row.names = 1)

metadata$Group <- recode(metadata$Group,
                          "Test-P" = "Patient",
                          "PTB" = "Patient",
                          "TB" = "Patient",
                          "HC" = "Health")
rownames(metadata) <- metadata$Sample

# Differential bacterial species.
Maaslin2(
  bacteria, metadata, "results/maaslin/bac",
  min_abundance = 0.01, min_prevalence = 0.01,
  normalization = "NONE",
  fixed_effects = c("Group", "Sex", "Age"),
  reference = c("Group,Patient"),
  plot_heatmap = TRUE, plot_scatter = TRUE
)

sig_bac <- read.delim("results/maaslin/bac/significant_results.tsv") %>%
  filter(metadata == "Group")
sig_vir <- read.delim("results/maaslin/vir/significant_results.tsv") %>%
  filter(metadata == "Group")

sig_bac_profile <- bacteria[rownames(bacteria) %in% sig_bac$feature, , drop = FALSE]
sig_vir_profile <- votu[rownames(votu) %in% sig_vir$feature, , drop = FALSE]

write.table(sig_bac_profile, "results/tables/sig_bac_spe.profile",
            quote = FALSE, sep = "\t")
write.table(sig_vir_profile, "results/tables/sig_vir_spe.profile",
            quote = FALSE, sep = "\t")

hc_list <- rownames(metadata)[metadata$Group == "Health"]
tb_list <- rownames(metadata)[metadata$Group == "Patient"]

hc_sig_vir <- sig_vir_profile[, intersect(colnames(sig_vir_profile), hc_list), drop = FALSE]
hc_sig_bac <- sig_bac_profile[, intersect(colnames(sig_bac_profile), hc_list), drop = FALSE]
tb_sig_vir <- sig_vir_profile[, intersect(colnames(sig_vir_profile), tb_list), drop = FALSE]
tb_sig_bac <- sig_bac_profile[, intersect(colnames(sig_bac_profile), tb_list), drop = FALSE]

select_occurrence <- function(x, threshold = 0.10) {
  if (ncol(x) == 0) stop("No samples available for occurrence filtering.")
  x[rowSums(x > 0) / ncol(x) > threshold, , drop = FALSE]
}

hc_selected_vir <- select_occurrence(hc_sig_vir)
hc_selected_bac <- select_occurrence(hc_sig_bac)
tb_selected_vir <- select_occurrence(tb_sig_vir)
tb_selected_bac <- select_occurrence(tb_sig_bac)

write.table(hc_selected_bac, "results/tables/hc_sig_bac.txt", quote = FALSE, sep = "\t")
write.table(hc_selected_vir, "results/tables/hc_sig_vir.txt", quote = FALSE, sep = "\t")
write.table(tb_selected_bac, "results/tables/tb_sig_bac.txt", quote = FALSE, sep = "\t")
write.table(tb_selected_vir, "results/tables/tb_sig_vir.txt", quote = FALSE, sep = "\t")

# Correlation calculation is performed by the user-supplied calc_corr.py.
# Run from results/tables or adapt -i/-I paths accordingly:
# python calc_corr.py -i hc_sig_vir.txt -I hc_sig_bac.txt -o hc_re.txt -s 0
# python calc_corr.py -i tb_sig_vir.txt -I tb_sig_bac.txt -o tb_re.txt -s 0

# BH correction and network edge filtering.
process_correlations <- function(input_file, output_file,
                                 corr_cutoff = 0.6, fdr_cutoff = 0.05) {
  re <- read.delim(input_file, check.names = FALSE)
  re$fdr <- p.adjust(re$pvalue, method = "BH")
  re_filter <- re %>%
    filter(abs(corr) >= corr_cutoff, fdr <= fdr_cutoff)
  write.table(re_filter, output_file, quote = FALSE, sep = "\t", row.names = FALSE)
  invisible(re_filter)
}

hc_sig_re <- process_correlations(
  "results/tables/hc_re.txt",
  "results/tables/hc_sig.re"
)

tb_sig_re <- process_correlations(
  "results/tables/tb_re.txt",
  "results/tables/tb_sig.re"
)

# hc_node.csv and tb_node.csv are exported from Cytoscape after network
# analysis and should be supplied under data/annotations/network/.
# They are NOT regenerated by this script.
