#!/bin/bash
# ==============================================================================
# PTB Virome Project
# script/run_rf_external.sh
# Build random forest models from training data, then predict external cohort.
# Missing features in external data are auto-filled with 0 by rf.py --fillna.
#
# Usage:  bash script/run_rf_external.sh <project_dir>
# ==============================================================================
set -euo pipefail

PROJECT_DIR="${1:-.}"
PROJECT_DIR="$(cd "${PROJECT_DIR}" && pwd)"

# ------------------------------------------------------------------------------
# Paths (mirror config.R)
# ------------------------------------------------------------------------------
RF_DIR="${PROJECT_DIR}/results/random_forest"
RF_PY="${PROJECT_DIR}/script/rf.py"
PYTHON="${RF_PYTHON:-python3}"
THREADS="${RF_THREADS:-10}"
N_EST="${RF_N_EST:-1000}"

# Training inputs (generated by 04c_random_forest.R)
TRAIN_SAMPLE_INFO="${RF_DIR}/sample_info.txt"
VIR_SORTED="${RF_DIR}/vir.sorted"
BAC_SORTED="${RF_DIR}/bac.sorted"
MERGE_SORTED="${RF_DIR}/merge.sorted"

# External inputs (raw files provided by user)
EXT_DIR="${PROJECT_DIR}/data/external"
EXT_VIR="${EXT_DIR}/votu.profile"
EXT_BAC="${EXT_DIR}/species_relative_abundance.tsv"
EXT_SAMPLE_INFO="${EXT_DIR}/sample_info.txt"

# Outputs
OUT_DIR="${RF_DIR}/external"

# ------------------------------------------------------------------------------
# Sanity checks
# ------------------------------------------------------------------------------
for f in "${TRAIN_SAMPLE_INFO}" "${VIR_SORTED}" "${BAC_SORTED}" "${MERGE_SORTED}"; do
    if [ ! -f "${f}" ]; then
        echo "[RF-ext] Missing training file: ${f}" >&2
        echo "         Please run 04c_random_forest.R first." >&2
        exit 1
    fi
done

for f in "${EXT_VIR}" "${EXT_BAC}" "${EXT_SAMPLE_INFO}"; do
    if [ ! -f "${f}" ]; then
        echo "[RF-ext] Missing external input: ${f}" >&2
        exit 1
    fi
done

if [ ! -f "${RF_PY}" ]; then
    echo "[RF-ext] rf.py not found at ${RF_PY}" >&2
    exit 1
fi

mkdir -p "${OUT_DIR}"
cd "${RF_DIR}"

# ------------------------------------------------------------------------------
# 1. Build models from training data (skip if already existing)
# ------------------------------------------------------------------------------
echo "[RF-ext] Building models..."
for pair in "vir:${VIR_SORTED}:virus_model.pkl" \
            "bac:${BAC_SORTED}:bac_model.pkl" \
            "merge:${MERGE_SORTED}:merge_model.pkl"; do
    IFS=":" read -r name profile model <<< "${pair}"
    if [ ! -f "${model}" ]; then
        echo "[RF-ext]   -> building ${model}"
        "${PYTHON}" "${RF_PY}" build \
            -i "${profile}" \
            -g "${TRAIN_SAMPLE_INFO}" \
            --threads "${THREADS}" --nest "${N_EST}" \
            -o "${model}"
    else
        echo "[RF-ext]   -> ${model} already exists, skipping."
    fi
done

# ------------------------------------------------------------------------------
# 2. Predict external cohort (--fillna handles missing features)
# ------------------------------------------------------------------------------
echo "[RF-ext] Predicting external cohort..."

"${PYTHON}" "${RF_PY}" predict \
    -i "${EXT_VIR}" -g "${EXT_SAMPLE_INFO}" \
    -M virus_model.pkl \
    -o "${OUT_DIR}/predict_re_virus.txt" --fillna

"${PYTHON}" "${RF_PY}" predict \
    -i "${EXT_BAC}" -g "${EXT_SAMPLE_INFO}" \
    -M bac_model.pkl \
    -o "${OUT_DIR}/predict_re_bac.txt" --fillna

# 合并模型需要同时包含病毒 + 细菌特征，把两张表拼起来即可（不需要样本对齐，
# rf.py 内部会按 -g 中的 Sample 做交集）
EXT_MERGE_TMP="${OUT_DIR}/ext_merge.profile"
if [ ! -f "${EXT_MERGE_TMP}" ]; then
    echo "[RF-ext]   -> constructing merged external profile"
    "${PYTHON}" - <<PYEOF
import pandas as pd
vir = pd.read_csv("${EXT_VIR}", sep="\t", index_col=0)
bac = pd.read_csv("${EXT_BAC}", sep="\t", index_col=0)
merged = pd.concat([vir, bac], axis=0)
merged.to_csv("${EXT_MERGE_TMP}", sep="\t")
PYEOF
fi

"${PYTHON}" "${RF_PY}" predict \
    -i "${EXT_MERGE_TMP}" -g "${EXT_SAMPLE_INFO}" \
    -M merge_model.pkl \
    -o "${OUT_DIR}/predict_re_merge.txt" --fillna

echo "[RF-ext] Done. Outputs in ${OUT_DIR}"